### ISSUE TITLE
Split the test file

### ISSUE THREAD

**Issue by roselmamendes** [nicolastrres/requestOn#17]
I am wondering would be interesting to split the test file. So it has a log_test.py and other request_service_test.py.
Thoughts?

**Comment by nicolastrres** [comment]
yep, that is an option. The other option is to split the file into unit tests, and maybe integration or functional tests. I think we only have unit tests at this moment, so it's seems a good option to split in log_test and request_service_test :+1:

**Comment by roselmamendes** [comment]
Great!
I am working on that :)
