### ISSUE TITLE
Find a way to break the build when pep8 fails

### ISSUE THREAD

**Issue by nicolastrres** [nicolastrres/requestOn#21]
Maybe try using tox and flake8. 
I found this repository that is doing this: https://snap-ci.com/SurveyMonkey/pycobertura/pull/25

**Comment by roselmamendes** [comment]
Did you try set -e in the beginning of the file?

I solved this kind of issue on Travis adding that.

**Comment by nicolastrres** [comment]
Oh I am going to try :+1:

**Comment by nicolastrres** [comment]
I tried putting -e in the run_tests.sh but -e is not a valid bash command :(

This is the output in snap-ci:
./run_tests.sh: line 2: -e: command not found
---------------------------Running PEP8---------------------------
------------------------------------------------------------------
---------------------------Running Tests--------------------------
.........
----------------------------------------------------------------------
Ran 9 tests in 3.094s

**Comment by nicolastrres** [comment]
@roselmamendes you were right, set -e works fine. :)
